variables:
- group: GitHub

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout'
- script: git push https://$(GitHubAccessToken)@github.com/hellikopter/ConcreteSupply-DataSchema.git
  displayName: 'Push to GitHub'